ansible_user: ubuntu
ansible_ssh_private_key_file: /home/shrinivas/.ssh/VinKey.pem
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
package_name: mysql-server
ansible_host: 13.204.143.170
web_port: 3306