---
- naame: install nginx using playbook variables
  hosts: webservers
  vars:
      package_name: nginx
      web_port: 80
      env: dev


  tasks:
    - name: install nginx using playbook variables
      apt:
        name: "{{ package_name }}"
        state: present
        update_cache: yes
      become: yes
    - name: Print data
      debug:
         msg: "Nginx will run on port {{ web_port }} in {{ env }} environment"     