all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/VinKey.pem
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"


    hosts:
      web1:
        ansible_host: 3.7.253.15
      web2:
        ansible_host: 65.1.111.158
         